version: '3.9'
services:
  bonfire-app:
    container_name: bonfire-app
    image: bonfire-app
    build:
      context: ./frontend/
      args:
        - APP_NAME=bonfire
        - APP_DIR=main
    ports:
    - '3000:3000'
    networks:
    - network
    depends_on:
      - keycloak
      - bonfire-worker
    environment:
    - NEXT_PUBLIC_API_URL=${PUBLIC_API_URL}
    - NEXT_PUBLIC_API_PORT=${PUBLIC_API_PORT}
    - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    - NEXTAUTH_URL=${NEXTAUTH_URL}
    - BONFIRE_ID=${BONFIRE_ID}
    - BONFIRE_CLIENT_SECRET=${BONFIRE_CLIENT_SECRET}
    - KEYCLOAK_ISSUER=${KC_ISSUER}
    restart: unless-stopped

  bonfire-admin:
    container_name: bonfire-admin
    image: bonfire-admin
    build:
      context: ./frontend/
      args:
        - APP_NAME=admin
        - APP_DIR=admin
    ports:
    - '3001:3000'
    networks:
    - network
    depends_on:
      - keycloak
      - bonfire-worker
    environment:
    - NEXT_PUBLIC_API_URL=${PUBLIC_API_URL}
    - NEXT_PUBLIC_API_PORT=${PUBLIC_API_PORT}
    - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    - NEXTAUTH_URL=${NEXTAUTH_URL}
    - BONFIRE_ID=${BONFIRE_ID}
    - BONFIRE_CLIENT_SECRET=${BONFIRE_CLIENT_SECRET}
    - KEYCLOAK_ISSUER=${KC_ISSUER}
    restart: unless-stopped

  bonfire-worker:
    container_name: bonfire-worker
    image: bonfire-worker
    build:
      context: ./backend/
    restart: always
    ports:
    - '${PUBLIC_API_PORT}:5000'
    environment:
    - DB_NAME=${DB_NAME}
    - DB_USER=${DB_USER}
    - DB_PASSWORD=${DB_PASSWORD}
    - KEYCLOAK_CLIENT_ID=${KC_CLIENT_ID}
    - KEYCLOAK_CLIENT_SECRET=${KC_CLIENT_SECRET}
    - KEYCLOAK_REALM_NAME=${KC_REALM_NAME}
    depends_on:
      - bonfire-db
      - keycloak
    networks:
    - network
    volumes:
      - ./backend/logs:/app/log

  bonfire-db:
    container_name: bonfire-db
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql      
    networks:
      - network

  keycloak:
    container_name: keycloak-app
    image: quay.io/keycloak/keycloak:23.0.6
    command: start-dev
    restart: unless-stopped
    depends_on:
      - keycloak-db
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB_URL=jdbc:postgresql://keycloak_db:5432/keycloak
      - KC_DB=postgres
      - KC_DB_USERNAME=${KC_DB_USER}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
    ports:
      - 5050:8080
    networks:
      - network

  keycloak-db:
    container_name: keycloak-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${KC_DB_USER}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
      POSTGRES_PORT: 5432
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  postgres_data:
